//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::todo_item::Entity")]
    TodoItem,
}

impl Related<super::todo_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TodoItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
